### PR TITLE
feat: supports multi endpoints and fix timestamp timezone

### LINKED ISSUE #6: support multiple endpoints

### PR DESCRIPTION
**Pull request by killme2008**
## What's changed and what's your intention?

1. Supports multi endpoints:

```go
cfg := greptime.NewConfig().
    WithDatabase("<database>").
    WithEndpoints("host1:4001", "host2:4001", "host3:4001").
    WithLoadBalancer(loadbalancer.NewRoundRobin()) // default is NewRandom()
```

2. Remove timezone info in timestamp types.

Close #6 

## Checklist

- [ ]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -298,33 +328,35 @@ func (c *Client) CloseStream(ctx context.Context) (*gpb.AffectedRows, error) {
...
+	c.stream = nil
+	c.streamMu.Unlock()
+
+	if c.pool != nil {
+		if err := c.pool.Close(); err != nil {
 			return err
 		}
-		c.conn = nil
+		c.pool = nil
 	}
```
Comment (MichaelScofield) [inline client.go]:
```suggestion
	if c.pool != nil {
	    p := c.pool
	    c.pool = nil
	    if err := p.Close(); err != nil {
		return err
	    }
	}
```

**Review by MichaelScofield — APPROVED** [review]

File: client.go (hunk 1 above)
Comment (killme2008) [reply client.go]: A better approach in https://github.com/GreptimeTeam/greptimedb-ingester-go/pull/101/commits/80cf09be0c46e634da0b069e6acbb180210943b0

**Review by daviderli614 — APPROVED** [review]
